#!/bin/sh

lb config noauto \
	--apt-indices true \
	--apt-options "--yes --no-install-recommends" \
	--apt-recommends false \
	--apt-source-archives false \
	-a i386 \
	--bootloader syslinux \
	--bootstrap debootstrap \
	--cache false \
	--cache-packages false \
	--checksums md5 \
	--debian-installer false \
	--debian-installer-gui false \
	-d sid \
	--iso-application "Kazsid" \
	--iso-publisher "Kazsid team" \
	--iso-volume "Kazsid_CD" \
	--initsystem systemd \
	-k 686-pae \
	--archive-areas "main contrib non-free" \
	--parent-mirror-bootstrap "http://127.0.0.1:3142/mirror.yandex.ru/debian/" \
	--mirror-bootstrap "http://127.0.0.1:3142/mirror.yandex.ru/debian/" \
	--parent-mirror-binary "http://mirror.yandex.ru/debian/" \
	--mirror-binary "http://mirror.yandex.ru/debian/" \
	--source false \
	--system live \
	--win32-loader false \
	--zsync false \
	"${@}"
